spring.application.name=CrudApi

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1

spring.datasource.username=SPRING_APP
spring.datasource.password=spring_app

spring.jpa.hibernate.ddl-auto=validate
